### ISSUE TITLE
TypeError: 'NoneType' object does not support item assignment

### ISSUE THREAD

**Issue by Silikin** [braindotai/Watermark-Removal-Pytorch#1]
So, after last update (5 days ago) does not work/
But before that update too didnt work

**Comment by braindotai** [comment]
Hi there, thanks for pointing out the issue. But can you be more specific about what part of the code you're facing this issue with and where exactly this error is popping up?

I just tested the training using `inference.py`, all is working fine, was not able to find any issues.

**Comment by Silikin** [comment]
> 

> 
> 
> Hi there, thanks for pointing out the issue. But can you be more specific about what part of the code you're facing this issue with and where exactly this error is popping up?
> 
> I just tested the training using `inference.py`, all is working fine, was not able to find any issues.

its work now. But if I have 200 images, how can I use the previous "training"?"

**Comment by braindotai** [comment]
> > 
> 
> > Hi there, thanks for pointing out the issue. But can you be more specific about what part of the code you're facing this issue with and where exactly this error is popping up?
> > I just tested the training using `inference.py`, all is working fine, was not able to find any issues.
> 
> its work now. But if I have 200 images, how can I use the previous "training"?"

You mean 200 watermarked images?
Yes you can indeed pass those image paths as described in doc string.

**Comment by Silikin** [comment]
But how (all photos)?)

**Comment by braindotai** [comment]
> But how (all photos)?)

Yes, you can either pass the image paths one by one with their map overlay, or you can also write a script that automates this passing of corresponding watermaked images and mask overlays present in a folder.
