### ISSUE TITLE
Not an issue. wondering if the set up is correct.

### ISSUE THREAD

**Issue by mobilelifeful** [braindotai/Watermark-Removal-Pytorch#11]
after changing the image in the watermarked folder. 
and masks in the masks folder. 

then run` python3 inference.py   `

```
(base) x@xnoMacBook-Pro Watermark-Removal-Pytorch % python3 inference.py   
Setting device to "cpu", since torch is not built with "cuda" support...
It is recommended to use GPU if possible...
Visualizing mask overlap...

```

got this message for a while.  Can you please confirm if the code is running as expected? Thank you.

**Comment by ryanhaticus** [comment]
A window should pop up with your mask preview.

**Comment by braindotai** [comment]
Yes, the code is working as expected, it's just that the processing would be slow since no GPU support is there in your system.
