### ISSUE TITLE
An iteration takes on my laptop dozens of seconds (cpu only)

### ISSUE THREAD

**Issue by matmay** [braindotai/Watermark-Removal-Pytorch#15]
How long should an iteration take? 

Is there any chance this will work quickly on my i7-4600u CPU with 10gb of ram on windows 10?

Currently I have an 1800x1200 image

**Comment by braindotai** [comment]
Can't say specifically, but yes it would take good amount of time on CPU, Id suggest to you GPU/Google Colab
