### ISSUE TITLE
retrain

### ISSUE THREAD

**Issue by Muhammadali-Akbarov** [braindotai/Watermark-Removal-Pytorch#16]
is it required that every time retrain for each image?

**Comment by braindotai** [comment]
Oh yeah, since I made this project quite a while back, so it is old tech :).

If you want a bit more instant watermark removal I'd suggest you try finding some other image inpainting projects made with stable diffusion, they'd be faster and more accurate

**Comment by TousenKaname** [comment]
Could you recommend some repos? :)
