### ISSUE TITLE
How to use the script?

### ISSUE THREAD

**Issue by yjmike** [braindotai/Watermark-Removal-Pytorch#2]
The script looks great! Unfortunately I am not a developer.  
May I ask how to use it?

I first downloaded it to my Mac, with GitHub Desktop.
Then I run the following in the terminal 

cd /Users/**MyUserName**/Documents/GitHub/Watermark-Removal-Pytorch/
python inference.py

It has the following error

Traceback (most recent call last):
  File "inference.py", line 2, in <module>
    from api import remove_watermark
  File "/Users/MyUserName/Documents/GitHub/Watermark-Removal-Pytorch/api.py", line 63
    print(f'\nSaving final output image to: "{output_path}"\n')
                                                             ^
SyntaxError: invalid syntax

Could you explain a little where I did it wrong?
Thanks in advance.
I would love to try this great script. 
Thanks for sharing

**Comment by braindotai** [comment]
Looks like you have python 2.x ... therefore f string is giving syntax error.
You can change that line like the one below, then you're good to go
```python
print('\nSaving final output image to:', output_path)
```

**Comment by yjmike** [comment]
I modified the line in api.py as above

Make it as
print('\nSaving final output image to:', output_path)

Then I run python inference.py

It has the following error: 
mac:Watermark-Removal-Pytorch MyUserName $ python inference.py
Traceback (most recent call last):
  File "inference.py", line 2, in <module>
    from api import remove_watermark
  File "/Users/MyUserName/Documents/GitHub/Watermark-Removal-Pytorch/api.py", line 1, in <module>
    from torch import optim
ImportError: No module named torch


I tried to install torch by
cd pytorch

Lots of files are downloaded inside my atermark-Removal-Pytorch folder as pytorch

I tried python inference.py
It still gives the above error

Can you script batch remove watermarks on multiple images?

**Comment by braindotai** [comment]
cd command doesn't install anything... It stands for change directory... You have to install pytorch through pip, head over to pytorch official website for complete installation guide based on your operating system.

And removing watermark for multiple images is not possible... It's just not how the model works.
You can try passing batch of images with batch of overlay masks but the outputs wouldn't be as good as compared to single image training.
