### ISSUE TITLE
Using the same model for the batch of images

### ISSUE THREAD

**Issue by AnimeLLove** [braindotai/Watermark-Removal-Pytorch#21]
Is it possible to use the same model for removing the watermark from thousands of images if watermark mask is the same?

**Comment by braindotai** [comment]
Yes its possible, but as per the current optimization function, the algorithm would not work well if batch inference is done. Watermark cleaning wouldn't be so clean. Also, the compute (specifically VRAM) requirement would be very high. I think for what you're mentioning would require bit more optimization calibration and training optimization.

I am planning to add half-precision training though, helping to run faster and produce more high resolution outputs on low vram devices. Coming soon...
