### ISSUE TITLE
CPU usage.

### ISSUE THREAD

**Issue by synrais** [braindotai/Watermark-Removal-Pytorch#23]
When set to CPU mode this sent a 13900k into 100% and made the cpu pulse/squeal with electronic noise. 
I have never had this before even stress testing.
I thought a hard drive was getting read its that loud!

**Comment by braindotai** [comment]
I can't comment anything about the hardware. Its strongly recommended to use dedicated Nvidia GPU instead of CPU, if you don't have one then you can use Google Colab for free :)
