### ISSUE TITLE
Model learns to synthesize watermark too

### ISSUE THREAD

**Issue by pnmartinez** [braindotai/Watermark-Removal-Pytorch#3]
Hi @braindotai ,

First of all, **thank you**!! This is definitely a nice wrapper for the original implementation, which is quite poorly documented.

I am in the second case: watermark not available; I am using a new file of my own. However, I am getting **nowhere close to your results**. The model learns to reproduce the watermark.

Am I doing sth wrong? Maybe the image format of the watermark?

Cheers.

**Comment by braindotai** [comment]
@pnmartinez Can you show me what the model is producing?
If the model is reproducing the watermark, then I guess you must have passed mask_path to image_path argument and vice versa in the function below:
```python
remove_watermark(
    image_path = ...,
    mask_path = ...,
    ....
)
```
Here's a [link to google colab with a live demo](https://colab.research.google.com/drive/1wgo9fUyQITyO7Eqwtaq2Q3fEyCv5asCJ?usp=sharing), you can have a further look at how you can use the wrapper, and how exactly the model learns to generate the outputs.
You can also obtain the mask overlay from [my website](https://brain-bust.web.app/projects/watermark-removal-using-deep-image-priors). Make sure to read the instructions under Live Demo section.

Hope this helps.

**Comment by braindotai** [comment]
hi @pnmartinez, I'm closing the issue for now because of inactivity... let me know if there's anything else I can help you with.
