### ISSUE TITLE
Licence? 

### ISSUE THREAD

**Issue by Birkenpapier** [braindotai/Watermark-Removal-Pytorch#5]
Hello,

really nice project!
Under which licence is it published?

**Comment by 564398053** [comment]
I'm not the author, It's MIT license now.
![image](https://user-images.githubusercontent.com/11308289/147527069-37dd9de8-f429-44a6-8b80-fee7c37b5fab.png)

**Comment by braindotai** [comment]
That's right!

**Comment by 564398053** [comment]
来信已收到，谢谢
